ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-cert
      hosts: 
        - optiva-registry
gitea:
  config:
    RUN_MODE: dev
    server:
      DOMAIN: optiva-registry
      PROTOCOL: https
      ROOT_URL: https://optiva-registry:32000/
      CERT_FILE: custom/tls.crt
      KEY_FILE: custom/tls.key
  admin:
    username: optiva
    password: password
    email: "optiva@optiva.com"
service:
  http:
    type: NodePort
    nodePort: 32000
extraVolumes:
  - name: gitea-cert-vol
    secret:
      secretName: gitea-cert
extraContainerVolumeMounts:
  - name: gitea-cert-vol
    readOnly: true
    mountPath: /data/gitea/custom
