ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /gitea(/|$)(.*)
          pathType: Prefix
gitea:
  config:
    server:
      ROOT_URL: http://0.0.0.0/gitea
      STATIC_URL_PREFIX: /gitea
