ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-cert
      hosts: 
        - optiva-registry
gitea:
  config:
    RUN_MODE: dev
    server:
      DOMAIN: optiva-registry
      PROTOCOL: https
      ROOT_URL: https://optiva-registry:32000/
      CERT_FILE: cert/cert.pem
      KEY_FILE: cert/key.pem
  admin:
    username: optiva
    password: password
    email: "optiva@optiva.com"
service:
  http:
    type: NodePort
    nodePort: 32000
extraDeploy:
  - |
    apiVersion: v1
      data:
        cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQU1yRVZVRzI1a0UwajZVdjE0UnRyV2t3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFUU1BNEdBMVVFQ2hNSFFXTnRaU0JEYnpFT01Bd0dBMVVFQXhNRlIybDBaV0V3SGhjTk1qTXdOekV3TVRBdwpORFEwV2hjTk1qUXdOekE1TVRBd05EUTBXakFpTVJBd0RnWURWUVFLRXdkQlkyMWxJRU52TVE0d0RBWURWUVFECkV3VkhhWFJsWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnVtN09WTnA5ZUQKYkd5enYvK09zZStoRUVCWGV0RTVQdkNVRk9xTXIrckZNUk0wbUV5VGdVZFJWSldYY1k5Y3d5bkZQVlNyanNXNwpJWGtJYS9BVVM2dVowMFkzdzNVbHdWYUJoZWw5aWliQU5KMjh5My9qazlJUVl3c044ODBTL3ZBSUlKK1JzUXBzCjNFNlRDQ3gvdE1paGNwcWdMYUhNUDNtVWhaSGhtUzZSMmxVejcvTjJkRTZMZWJuUUlVOE9Ha1UwRVFySjh3YWQKVVNCT204T2dPSjF4Z214Z0xETG1ua283SjluS081L2E0V0prVUZlYzIybVdoMG1DWXdycDJkZWUxZncvRE9GMgo3QmJvYnBlTGdKUjR5bTNLVUJwNTVJOFEzSVZZSmc4cW42Z1dlTVJtTG5hRFVaV2t6cGMzcUZLemVrbkhrK0NLCmhCT0hQMUJ4T0lVQ0F3RUFBYU5STUU4d0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0cKQVFVRkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBd0dnWURWUjBSQkJNd0VZSVBiM0IwYVhaaExYSmxaMmx6ZEhKNQpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNhd0tudTJ2K08rV3VlNkhlUkFId2VXZVFoNHNoaUppZkl5UC9hClRjeGY0TTY4aENyaDJIUWFPM1pDM0taUTgzWFdmbjBGVXFLOWV0R0RHMDkxS1JPVXlrdmQxZzRGWTNUMGdXK2QKTVgrb3grU1Y1Q2RldmxreXA1ZVdXK1Nudi9JRjdqeno1ZTZXNk02Sk5xMzZmaHViM1BjbVAvUXByMXdFL1hIagpGUE1xUlNZSUYvTHdpV2JGcHorTWpUR1hVZVhoNDhtYVpFa2xleHd3U1FWVURzWVRxeWdiamRzUmE0K2g2Y0tECkJmcElHZGlWVjJMQitFbnpTYnY1ZW1KRkN5UTFNYUFqQktKWEdGRWVFU3N1YmhDeUFDKzlsL1ZPZXhZMThTaWwKYXVCZ2c4SmhsYWlWUUdwWGVMb2YzMGgzY05VankwUHE5TVBEN0d4a3dBT0sxdWxPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBbTZiczVVMm4xNE5zYkxPLy80Nng3NkVRUUZkNjBUays4SlFVNm95djZzVXhFelNZClRKT0JSMUZVbFpkeGoxekRLY1U5Vkt1T3hic2hlUWhyOEJSTHE1blRSamZEZFNYQlZvR0Y2WDJLSnNBMG5iekwKZitPVDBoQmpDdzN6elJMKzhBZ2duNUd4Q216Y1RwTUlMSCsweUtGeW1xQXRvY3cvZVpTRmtlR1pMcEhhVlRQdgo4M1owVG90NXVkQWhUdzRhUlRRUkNzbnpCcDFSSUU2Ync2QTRuWEdDYkdBc011YWVTanNuMmNvN245cmhZbVJRClY1emJhWmFIU1lKakN1bloxNTdWL0Q4TTRYYnNGdWh1bDR1QWxIaktiY3BRR25ua2p4RGNoVmdtRHlxZnFCWjQKeEdZdWRvTlJsYVRPbHplb1VyTjZTY2VUNElxRUU0Yy9VSEU0aFFJREFRQUJBb0lCQUFGc3pjNXJuNVhCaGtTWQpnTEYrUlBMRXJybG9FNS9Hdm1URmRrdVBiaXpnRVVyenVGRTdLSHZXcXNlVDAxNVVveFRHMFlEczhTbXVST2d1Cnc0NDNJVm80MWs1V1JGdldOS2J1R0tQQ21ua3dXVXI0WjRTTU9OWTdnQ3lodkJHc2t0anZ1aHk3NExzUHRCU2sKRS9jVVZEdGgvd0tiWk0rT1p5WmR6YnRBTFg3WG8xZ3pCWHB5U0xuZm45YmhicFBNby9rdm9uRys5WVRSNjljMwo5U0ZCbDd2Mm1rZURKeWgxRlplanJCNHlYenJia3Q3bVZGQlQ2di8yV3M1czZBUW84OHdiVkdkUXFXcEN6ZFBTCldxcWZaZkRwNHFCQmg3ZTQzb0Jyc1A0SDZBOGVWKzFVZ1gvRGJpSEFtdDMwMHpRS25CU2VSWHNIZ2UwT2h1ZlkKMCtVS01DRUNnWUVBdzhrS1I1ZzJ5UlhQakJJSlVUY0NXNG40ZFRJSWdOc2V6enpCSFprVjJsRER2RURRNGpsZgorWVFsUUlFbm5xenZRalZLaSt5bHB3bFUrQXd2ZmxVd2drclJISFprbVJtWWhPU2c2NXF6SG1qbHlaWE1kRzYyCmpuZ29ESGY2RnpnSHpOVCsvS21tcngrNjNpbnE1eGpIdWtWLzdNRkdla3lkRFZtMy9TUTN5RnNDZ1lFQXk0WUkKZytQaUo3MjBYdTdxQitONUVaUWxsRzVYOGtPZ1c5c2EvMXJmUjNMdllKTU9KazBNbUlTeFVGeXhYVWNPdVcxeApKSkJwMW85Mi9kY0w0TmR4cmlOYzNmRHJOUmY5RmR6ZVYrZDcrNk1kY0pIem9Sd25GSytTNEdKUk9EZGtGWVliClpjMk5NZ2pRdUUwak9RdFJLR2hibmd0Ky9GTGhpSHg3dmZadDJKOENnWUJvcUZvM1pWVzc3azNSQ1g4emk5MVYKdzQ0dVQ3MmQ3QVF2TWNIbHFZUzEvRUIxckl3OHNnRHM1OGZtRUdSMmZPazFFam0wVEo5TWlEK0VqVGNDS0ZYVApBRjJDQW9QS0Y1V2hUSG45RitneUZFN3BrSXNIbm5zMTgyTXRMeUZnTWhKeFcxYW5CNlZUcmZsOWN4amZ5aTVTCkUzN0x0NUdPSk5BN1o3OWpzVzJrU3dLQmdCUXRJSEQ2eVhQSkliVjdsK1hhVGlsSTk0VEVmNkY3eE16MlpySEQKNzNpazAwaE9xOHR1UGY1c3dTdEhWU243SG1HUmtQTGdBaTRNSU82L1ArVTFWb2E5NkxuejVVMXBLR1RmZFlkZgpZbklxMUlOUlpNYW5CTlRQSnc5cGo4V3o4QThXTVdjaFBvc2tScFRPeU53aDNCVFdhNmE2V3dkbXJBY2MyQ09YCjU0SGZBb0dBWTNYLzlZekhtK1FQdEIwZnVPOTQ3dU1xTUptMlRrcUxGdGlYeXNiRmR3em1lVEYyUW5qOUw3dHQKUGtIRUhTWXNxcnRiTjNIamFmMHg0VnlCcURVcndWcE5qUEwwd2hvblMyNDkyQU1HVEhSNjJEQU8yeVpXSStDOApNTy8wYm1PRGdPdXZwNzlRb3R5MXRHRmppbEJlcnJkUW82Y2UzTTlhOWlBUkhWK2ZlUTg9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
      kind: Secret
    metadata:
      name: gitea-cert
    type: Opaque
extraVolumes:
  - name: gitea-cert-vol
    secret:
      secretName: gitea-cert
extraContainerVolumeMounts:
  - name: gitea-cert-vol
    mountPath: /data/gitea/cert
