ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-cert
      hosts: 
        - optiva-registry
gitea:
  config:
    RUN_MODE: dev
    server:
      DOMAIN: registry.optiva.com
      PROTOCOL: https
      ROOT_URL: https://registry.optiva.com:32000/
      CERT_FILE: cert/tls.crt
      KEY_FILE: cert/tls.key
    log:
      LEVEL: Trace
  admin:
    username: optiva
    password: password
    email: "optiva@optiva.com"
service:
  http:
    type: NodePort
    nodePort: 32000
extraVolumes:
  - name: gitea-cert-vol
    secret:
      secretName: gitea-cert
extraContainerVolumeMounts:
  - name: gitea-cert-vol
    mountPath: /data/gitea/cert
