ingress:
  enabled: true
  className: nginx
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: /
#        - path: /gitea(/|$)(.*)
#          pathType: Prefix
gitea:
  config:
    server:
      ROOT_URL: http://localhost:3000
#      ROOT_URL: http://0.0.0.0:3000/gitea
#      STATIC_URL_PREFIX: /gitea
  admin:
    username: gitea
    password: password
    email: "gitea@optiva.com"
