ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
gitea:
  config:
    server:
      DOMAIN: optiva-registry
      ROOT_URL: http://optiva-registry:32000/
  admin:
    username: optiva
    password: password
    email: "optiva@optiva.com"
service:
  http:
    type: NodePort
    nodePort: 32000
