ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
gitea:
  config:
    server:
      ROOT_URL: http://localhost:3000
  admin:
    username: gitea
    password: password
    email: "gitea@optiva.com"
