ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: /gitea(/|$)(.*)
          pathType: Prefix
gitea:
  config:
    server:
      ROOT_URL: http://0.0.0.0/gitea
      STATIC_URL_PREFIX: /gitea
  admin:
    username: admin
    password: password
    email: "admin@optiva.com"
