ingress:
  enabled: true
  className: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-cert
      hosts: 
        - optiva-registry
gitea:
  config:
    server:
      DOMAIN: optiva-registry
      PROTOCOL: https
      ROOT_URL: https://optiva-registry:32000/
  admin:
    username: optiva
    password: password
    email: "optiva@optiva.com"
service:
  http:
    type: NodePort
    nodePort: 32000
