prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
prometheusOperator:
  admissionWebhooks:
    failurePolicy: Ignore
grafana:
  grafana.ini:
    server:
      domain: localhost
      root_url: http://localhost:3000/grafana/
      serve_from_sub_path: true
  ingress:
    enabled: true
    path: "/grafana"
